version: '3'

services:
  backend:
    build: ./backend
    ports: 
      - "8000:8000"
    env_file:
      - ./backend/.env 


  frontend:     
    build: ./frontend
    ports: 
      - "3000:3000"
    env_file:
      - ./frontend/.env 
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000/api

  websockets:
    build: ./websockets
    ports: 
      - "3001:3001"
    env_file:
      - ./websockets/.env 